/**
 * Webhook Manager Component
 * Manage webhook endpoints and configurations for real-time updates
 */

import React, { useState, useCallback } from 'react';
import { toast } from 'sonner';
import { useIntegrationFramework } from '@/hooks/useIntegrationFramework';
import type { WebhookEndpoint, WebhookEventType } from '@/types/integrations';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import { Separator } from '@/components/ui/separator';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Webhook,
  Plus,
  MoreHorizontal,
  Trash2,
  Copy,
  RefreshCw,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Eye,
  ExternalLink,
  Key,
} from 'lucide-react';

interface WebhookManagerProps {
  integrationId?: number;
}

const webhookEvents: { value: WebhookEventType; label: string; description: string }[] = [
  { value: 'task.created', label: 'Task Created', description: 'When a new task is created' },
  { value: 'task.updated', label: 'Task Updated', description: 'When a task is modified' },
  { value: 'task.deleted', label: 'Task Deleted', description: 'When a task is deleted' },
  { value: 'task.status_changed', label: 'Status Changed', description: 'When a task status changes' },
  { value: 'task.assigned', label: 'Task Assigned', description: 'When a task is assigned' },
  { value: 'comment.added', label: 'Comment Added', description: 'When a comment is added' },
  { value: 'attachment.added', label: 'Attachment Added', description: 'When an attachment is uploaded' },
  { value: 'project.created', label: 'Project Created', description: 'When a new project is created' },
  { value: 'project.updated', label: 'Project Updated', description: 'When a project is modified' },
];

export const WebhookManager: React.FC<WebhookManagerProps> = ({ integrationId }) => {
  const {
    webhookEndpoints,
    refreshWebhookEndpoints,
    createWebhookEndpoint,
    updateWebhookEndpoint,
    deleteWebhookEndpoint,
    regenerateWebhookSecret,
    isLoadingWebhooks,
  } = useIntegrationFramework();

  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isViewDialogOpen, setIsViewDialogOpen] = useState(false);
  const [selectedEndpoint, setSelectedEndpoint] = useState<WebhookEndpoint | null>(null);
  const [showSecrets, setShowSecrets] = useState<Record<number, boolean>>({});
  
  // Confirmation dialog state
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [regenerateDialogOpen, setRegenerateDialogOpen] = useState(false);
  const [pendingEndpointId, setPendingEndpointId] = useState<number | null>(null);

  // Form state
  const [newEndpoint, setNewEndpoint] = useState<Partial<WebhookEndpoint>>({
    name: '',
    url: '',
    events: [],
    isActive: true,
  });

  const handleRefresh = useCallback(async () => {
    await refreshWebhookEndpoints(integrationId);
    toast.success('Webhooks refreshed');
  }, [refreshWebhookEndpoints, integrationId]);

  const handleCreate = useCallback(async () => {
    if (!newEndpoint.name || !newEndpoint.url || newEndpoint.events?.length === 0) {
      toast.error('Please fill in all required fields');
      return;
    }

    const success = await createWebhookEndpoint({
      name: newEndpoint.name,
      url: newEndpoint.url,
      events: newEndpoint.events as WebhookEventType[],
      isActive: newEndpoint.isActive ?? true,
      secret: '', // Will be generated by backend
      organizationId: 0, // Will be set by backend
    });

    if (success) {
      setIsCreateDialogOpen(false);
      setNewEndpoint({ name: '', url: '', events: [], isActive: true });
    }
  }, [newEndpoint, createWebhookEndpoint]);

  const handleDelete = useCallback(async (endpointId: number) => {
    setPendingEndpointId(endpointId);
    setDeleteDialogOpen(true);
  }, []);
  
  const confirmDelete = useCallback(async () => {
    if (pendingEndpointId !== null) {
      await deleteWebhookEndpoint(pendingEndpointId);
    }
    setDeleteDialogOpen(false);
    setPendingEndpointId(null);
  }, [pendingEndpointId, deleteWebhookEndpoint]);

  const handleToggleActive = useCallback(async (endpoint: WebhookEndpoint) => {
    await updateWebhookEndpoint(endpoint.id, { isActive: !endpoint.isActive });
  }, [updateWebhookEndpoint]);

  const handleCopySecret = useCallback((secret: string) => {
    navigator.clipboard.writeText(secret);
    toast.success('Secret copied to clipboard');
  }, []);

  const handleRegenerateSecret = useCallback(async (endpointId: number) => {
    setPendingEndpointId(endpointId);
    setRegenerateDialogOpen(true);
  }, []);
  
  const confirmRegenerate = useCallback(async () => {
    if (pendingEndpointId !== null) {
      await regenerateWebhookSecret(pendingEndpointId);
    }
    setRegenerateDialogOpen(false);
    setPendingEndpointId(null);
  }, [pendingEndpointId, regenerateWebhookSecret]);

  const toggleEvent = (event: WebhookEventType) => {
    setNewEndpoint(prev => ({
      ...prev,
      events: prev.events?.includes(event)
        ? prev.events.filter(e => e !== event)
        : [...(prev.events || []), event],
    }));
  };

  const getStatusIcon = (endpoint: WebhookEndpoint) => {
    if (!endpoint.isActive) return <XCircle className="h-4 w-4 text-gray-400" />;
    if (endpoint.lastError) return <AlertCircle className="h-4 w-4 text-amber-500" />;
    return <CheckCircle2 className="h-4 w-4 text-green-500" />;
  };

  const getStatusBadge = (endpoint: WebhookEndpoint) => {
    if (!endpoint.isActive) return <Badge variant="secondary">Inactive</Badge>;
    if (endpoint.lastError) return <Badge variant="destructive">Error</Badge>;
    return <Badge variant="default" className="bg-green-600">Active</Badge>;
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-medium flex items-center gap-2">
            <Webhook className="h-5 w-5" />
            Webhook Endpoints
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Configure webhooks to receive real-time updates
          </p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleRefresh}
            disabled={isLoadingWebhooks}
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${isLoadingWebhooks ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
          <Button size="sm" onClick={() => setIsCreateDialogOpen(true)}>
            <Plus className="h-4 w-4 mr-2" />
            Add Endpoint
          </Button>
        </div>
      </div>

      {webhookEndpoints.length === 0 ? (
        <Card className="border-dashed">
          <CardContent className="py-8 text-center">
            <Webhook className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium">No webhook endpoints</h3>
            <p className="text-sm text-muted-foreground mt-1 max-w-sm mx-auto">
              Create webhook endpoints to receive real-time notifications when tasks and projects change.
            </p>
            <Button className="mt-4" onClick={() => setIsCreateDialogOpen(true)}>
              <Plus className="h-4 w-4 mr-2" />
              Create First Endpoint
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Status</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>URL</TableHead>
                <TableHead>Events</TableHead>
                <TableHead>Last Triggered</TableHead>
                <TableHead className="w-[50px]"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {webhookEndpoints.map((endpoint) => (
                <TableRow key={endpoint.id}>
                  <TableCell>{getStatusIcon(endpoint)}</TableCell>
                  <TableCell>
                    <div className="font-medium">{endpoint.name}</div>
                    {getStatusBadge(endpoint)}
                  </TableCell>
                  <TableCell>
                    <code className="text-xs bg-muted px-2 py-1 rounded truncate max-w-[200px] block">
                      {endpoint.url}
                    </code>
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline">{endpoint.events.length} events</Badge>
                  </TableCell>
                  <TableCell>
                    {endpoint.lastTriggeredAt
                      ? new Date(endpoint.lastTriggeredAt).toLocaleDateString()
                      : 'Never'}
                  </TableCell>
                  <TableCell>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon">
                          <MoreHorizontal className="h-4 w-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem
                          onClick={() => {
                            setSelectedEndpoint(endpoint);
                            setIsViewDialogOpen(true);
                          }}
                        >
                          <Eye className="h-4 w-4 mr-2" />
                          View Details
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleToggleActive(endpoint)}>
                          {endpoint.isActive ? (
                            <>
                              <XCircle className="h-4 w-4 mr-2" />
                              Deactivate
                            </>
                          ) : (
                            <>
                              <CheckCircle2 className="h-4 w-4 mr-2" />
                              Activate
                            </>
                          )}
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleRegenerateSecret(endpoint.id)}>
                          <Key className="h-4 w-4 mr-2" />
                          Regenerate Secret
                        </DropdownMenuItem>
                        <DropdownMenuItem
                          className="text-destructive"
                          onClick={() => handleDelete(endpoint.id)}
                        >
                          <Trash2 className="h-4 w-4 mr-2" />
                          Delete
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}

      {/* Create Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Create Webhook Endpoint</DialogTitle>
            <DialogDescription>
              Add a new endpoint to receive real-time event notifications
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input
                id="name"
                value={newEndpoint.name}
                onChange={(e) => setNewEndpoint(prev => ({ ...prev, name: e.target.value }))}
                placeholder="e.g., My Integration Webhook"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="url">Endpoint URL</Label>
              <Input
                id="url"
                value={newEndpoint.url}
                onChange={(e) => setNewEndpoint(prev => ({ ...prev, url: e.target.value }))}
                placeholder="https://api.example.com/webhooks/taskluid"
              />
              <p className="text-xs text-muted-foreground">
                Must be a valid HTTPS URL
              </p>
            </div>

            <div className="space-y-2">
              <Label>Events to Subscribe</Label>
              <div className="space-y-2 max-h-[200px] overflow-y-auto border rounded-md p-3">
                {webhookEvents.map((event) => (
                  <div key={event.value} className="flex items-start space-x-2">
                    <Checkbox
                      id={event.value}
                      checked={newEndpoint.events?.includes(event.value)}
                      onCheckedChange={() => toggleEvent(event.value)}
                    />
                    <div className="grid gap-0.5">
                      <Label htmlFor={event.value} className="text-sm font-medium">
                        {event.label}
                      </Label>
                      <p className="text-xs text-muted-foreground">{event.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex items-center space-x-2">
              <Switch
                id="active"
                checked={newEndpoint.isActive}
                onCheckedChange={(checked) =>
                  setNewEndpoint(prev => ({ ...prev, isActive: checked }))
                }
              />
              <Label htmlFor="active">Active</Label>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleCreate}>
              Create Endpoint
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* View Details Dialog */}
      <Dialog open={isViewDialogOpen} onOpenChange={setIsViewDialogOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Webhook Endpoint Details</DialogTitle>
          </DialogHeader>

          {selectedEndpoint && (
            <div className="space-y-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-xs text-muted-foreground">Name</Label>
                  <p className="font-medium">{selectedEndpoint.name}</p>
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Status</Label>
                  <div className="mt-1">{getStatusBadge(selectedEndpoint)}</div>
                </div>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">URL</Label>
                <code className="block text-sm bg-muted px-2 py-1 rounded mt-1 break-all">
                  {selectedEndpoint.url}
                </code>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">Webhook Secret</Label>
                <div className="flex items-center gap-2 mt-1">
                  <code className="flex-1 text-sm bg-muted px-2 py-1 rounded font-mono">
                    {showSecrets[selectedEndpoint.id]
                      ? selectedEndpoint.secret
                      : '••••••••••••••••••••••••••'}
                  </code>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() =>
                      setShowSecrets(prev => ({
                        ...prev,
                        [selectedEndpoint.id]: !prev[selectedEndpoint.id],
                      }))
                    }
                  >
                    <Eye className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => handleCopySecret(selectedEndpoint.secret)}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  Use this secret to verify webhook signatures
                </p>
              </div>

              <div>
                <Label className="text-xs text-muted-foreground">Subscribed Events</Label>
                <div className="flex flex-wrap gap-2 mt-1">
                  {selectedEndpoint.events.map((event) => (
                    <Badge key={event} variant="outline">
                      {webhookEvents.find(e => e.value === event)?.label || event}
                    </Badge>
                  ))}
                </div>
              </div>

              <Separator />

              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <Label className="text-xs text-muted-foreground">Created</Label>
                  <p>{new Date(selectedEndpoint.createdAt).toLocaleString()}</p>
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Last Triggered</Label>
                  <p>
                    {selectedEndpoint.lastTriggeredAt
                      ? new Date(selectedEndpoint.lastTriggeredAt).toLocaleString()
                      : 'Never'}
                  </p>
                </div>
              </div>

              {selectedEndpoint.lastError && (
                <div className="rounded-md bg-destructive/10 p-3">
                  <Label className="text-xs text-destructive">Last Error</Label>
                  <p className="text-sm text-destructive mt-1">{selectedEndpoint.lastError}</p>
                </div>
              )}
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setIsViewDialogOpen(false)}>
              Close
            </Button>
            <Button
              variant="destructive"
              onClick={() => {
                if (selectedEndpoint) {
                  handleDelete(selectedEndpoint.id);
                  setIsViewDialogOpen(false);
                }
              }}
            >
              <Trash2 className="h-4 w-4 mr-2" />
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Webhook Endpoint</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this webhook endpoint? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setPendingEndpointId(null)}>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete} className="bg-destructive text-destructive-foreground">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Regenerate Secret Confirmation Dialog */}
      <AlertDialog open={regenerateDialogOpen} onOpenChange={setRegenerateDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Regenerate Secret</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure? This will invalidate the current secret and generate a new one.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setPendingEndpointId(null)}>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmRegenerate}>
              Regenerate
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

export default WebhookManager;
